type PubM {
  login (username: ID!, password: String!): UserAndError!
  signup (
    username: ID!,
    password: String!,
    email: String!,
    firstName: String,
    lastName: String
  ): UserAndError
}
