// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package prv

type Error struct {
	Field    string   `json:"field"`
	Messages []string `json:"messages"`
}

type ErrorList struct {
	Errors []*Error `json:"errors"`
}

func (ErrorList) IsUserAndError()  {}
func (ErrorList) IsTokenAndError() {}

type Token struct {
	Token string `json:"token"`
}

func (Token) IsTokenAndError() {}

type TokenAndError interface {
	IsTokenAndError()
}

type User struct {
	Username  string  `json:"username"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
}

func (User) IsUserAndError() {}

type UserAndError interface {
	IsUserAndError()
}
