// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package pub

type Error struct {
	Field    string   `json:"field"`
	Messages []string `json:"messages"`
}

type User struct {
	Username  string  `json:"username"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
}
